# Generated by Django 4.0 on 2022-01-21 11:18

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0002_banner_blog_remove_cycle_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_one",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="ads"
                    ),
                ),
                (
                    "image_two",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="ads"
                    ),
                ),
                (
                    "image_ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=150)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="brands"
                    ),
                ),
                (
                    "image_ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20
                    ),
                ),
            ],
        ),
    ]
