# Generated by Django 4.0 on 2022-02-09 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "officialapi",
            "0005_rename_recieved_date_cycle_service_attended_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="cycle",
            old_name="model_no",
            new_name="model_name",
        ),
    ]
