# Generated by Django 4.0 on 2022-02-11 06:31

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0006_rename_model_no_cycle_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="customer_address",
            field=tinymce.models.HTMLField(
                blank=True, max_length=400, null=True, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="fitness",
            name="customer_address",
            field=tinymce.models.HTMLField(
                blank=True, max_length=400, null=True, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="fitness",
            name="remark",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
