# Generated by Django 4.0 on 2022-02-15 09:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0007_alter_cycle_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="service_request",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together={("complaint", "category", "branch")},
        ),
        migrations.CreateModel(
            name="model_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="officialapi.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "branch")},
            },
        ),
        migrations.AlterField(
            model_name="cycle",
            name="model_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="officialapi.model_name",
            ),
        ),
    ]
