# Generated by Django 4.0 on 2022-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "officialapi",
            "0008_alter_complaint_unique_together_complaint_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="category",
            field=models.CharField(
                choices=[
                    ("fitness", "fitness"),
                    ("cycle", "cycle"),
                    ("badminton", "badminton"),
                ],
                default=1,
                max_length=70,
            ),
            preserve_default=False,
        ),
    ]
