# Generated by Django 4.0 on 2022-02-18 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0009_technician_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="department",
        ),
    ]
