# Generated by Django 4.0 on 2022-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0010_remove_technician_department"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("name", "branch", "category")},
        ),
    ]
