# Generated by Django 4.0 on 2022-03-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officialapi", "0011_alter_brand_unique_together_brand_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("entry", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=70)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="officialapi.service_request",
                    ),
                ),
            ],
        ),
    ]
